<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Payment Receipt</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #111827; }
        .container { max-width: 720px; margin: 0 auto; padding: 24px; }
        .header { display:flex; justify-content: space-between; align-items:center; margin-bottom: 24px; }
        .brand { display:flex; align-items:center; gap:12px; }
        .logo { width:40px; height:40px; background: linear-gradient(90deg,#2563eb,#4f46e5); border-radius:12px; }
        .title { font-size: 20px; font-weight: 700; }
        .muted { color: #6b7280; font-size: 12px; }
        .card { border: 1px solid #e5e7eb; border-radius: 12px; padding: 16px; margin-bottom: 16px; }
        .row { display:flex; gap:16px; }
        .col { flex:1; }
        .label { color:#6b7280; font-size:12px; }
        .value { font-size:14px; font-weight:600; }
        .totals { text-align:right; margin-top: 12px; }
        .currency-info { background: #f3f4f6; padding: 12px; border-radius: 8px; margin-top: 12px; }
    </style>
 </head>
 <body>
    <div class="container">
        <div class="header">
            <div class="brand">
                <div class="logo"></div>
                <div>
                    <div class="title">SiteManager</div>
                    <div class="muted">Payment Receipt</div>
                </div>
            </div>
            <div class="muted">{{ now()->format('M d, Y') }}</div>
        </div>

        <div class="card">
            <div class="row">
                <div class="col">
                    <div class="label">Receipt #</div>
                    <div class="value">{{ $payment->receipt_number ?? ('RCT-' . strtoupper($payment->id)) }}</div>
                </div>
                <div class="col">
                    <div class="label">Date</div>
                    <div class="value">{{ optional($payment->payment_date)->format('M d, Y') }}</div>
                </div>
            </div>
            <div class="row" style="margin-top:12px;">
                <div class="col">
                    <div class="label">Client Website</div>
                    <div class="value">{{ $payment->website->name ?? 'N/A' }}</div>
                    <div class="muted">{{ $payment->website->domain ?? '' }}</div>
                </div>
                <div class="col">
                    <div class="label">Payment Method</div>
                    <div class="value">{{ $payment->payment_method }}</div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="row">
                <div class="col">
                    <div class="label">Amount</div>
                    <div class="value">
                        @if($payment->currency === 'UGX')
                            USh {{ number_format($payment->amount, 0) }}
                        @elseif($payment->currency === 'USD')
                            ${{ number_format($payment->amount, 2) }}
                        @elseif($payment->currency === 'EUR')
                            €{{ number_format($payment->amount, 2) }}
                        @elseif($payment->currency === 'GBP')
                            £{{ number_format($payment->amount, 2) }}
                        @elseif($payment->currency === 'KES')
                            KSh {{ number_format($payment->amount, 2) }}
                        @elseif($payment->currency === 'TZS')
                            TSh {{ number_format($payment->amount, 2) }}
                        @elseif($payment->currency === 'NGN')
                            ₦{{ number_format($payment->amount, 2) }}
                        @else
                            {{ $payment->currency }} {{ number_format($payment->amount, 2) }}
                        @endif
                    </div>
                </div>
                <div class="col">
                    <div class="label">Status</div>
                    <div class="value">{{ ucfirst($payment->status) }}</div>
                </div>
            </div>
            <div class="currency-info">
                <div class="label">USD Equivalent</div>
                <div class="value">${{ number_format($payment->usd_equivalent ?? 0, 2) }}</div>
            </div>
            @if($payment->transaction_id)
            <div class="row" style="margin-top:12px;">
                <div class="col">
                    <div class="label">Transaction ID</div>
                    <div class="value">{{ $payment->transaction_id }}</div>
                </div>
            </div>
            @endif
        </div>

        @if($payment->notes)
            <div class="card">
                <div class="label">Notes</div>
                <div class="value" style="font-weight: normal;">{{ $payment->notes }}</div>
            </div>
        @endif

        <div class="muted" style="margin-top:16px;">This receipt was generated by SiteManager.</div>
    </div>
 </body>
 </html>


